// Zero-dependency static site build: `npm run build` → ./dist
import { mkdirSync, rmSync, writeFileSync, cpSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { site } from './src/site.mjs';
import { layout } from './src/layout.mjs';
import { setPage, todoLog } from './src/lib.mjs';
import { work } from './src/content/work.mjs';
import * as P from './src/pages.mjs';

const OUT = 'dist';
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
if (existsSync('public')) cpSync('public', OUT, { recursive: true });

const pages = [
  P.home,
  P.workIndex,
  ...work.map((w, i) => () => P.caseStudy(w, i)),
  P.servicesPage,
  P.aboutPage,
  P.contactPage,
  P.archivePage,
  P.notFound,
];

const urls = [];
for (const make of pages) {
  // Render once to learn the path, then again with the page set for TODO logging.
  setPage('');
  const page = make();
  setPage(page.path);
  const final = make();
  const html = layout(final);
  const file = final.path.endsWith('.html') ? join(OUT, final.path) : join(OUT, final.path, 'index.html');
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, html);
  if (!final.path.endsWith('.html')) urls.push(final.path);
}

// The first render of each page also logged TODOs; keep unique entries only.
const seen = new Set();
const todos = todoLog.filter((t) => t.page && !seen.has(t.page + t.text) && seen.add(t.page + t.text));

writeFileSync(
  join(OUT, 'sitemap.xml'),
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls
    .map((u) => `  <url><loc>${site.url}${u}</loc></url>`)
    .join('\n')}\n</urlset>\n`
);
writeFileSync(join(OUT, 'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${site.url}/sitemap.xml\n`);

const strip = (s) => s.replace(/<[^>]+>/g, '');
writeFileSync(
  'CONTENT-TODO.md',
  `# Content checklist\n\nGenerated by \`npm run build\`. Every item below shows on the site as a TODO note until you fill it in.\n\n${Object.entries(
    todos.reduce((acc, t) => ((acc[t.page] ||= []).push(t.text), acc), {})
  )
    .map(([page, items]) => `## ${page}\n\n${items.map((i) => `- [ ] ${strip(i)}`).join('\n')}`)
    .join('\n\n')}\n`
);

console.log(`Built ${pages.length} pages → ${OUT}/ (${todos.length} TODO notes, see CONTENT-TODO.md)`);
